### ISSUE TITLE
Feature request - Push notification of new incoming mail

### ISSUE THREAD

**Issue by RaviGaruda** [Enough-Software/enough_mail_app#1]

**Comment by robert-virkus** [comment]
Agreed :-)
However, I see several ways how to achieve this:
1. Traditionally, you hand over your email credentials to a service that constantly monitors your mailbox and informs you via push notifications when a new message is received.
2. At least on Android you can ask the user to allow the mail app to always run, doing the checks itself. In this way your credentials do not leave your device.
3. You can also query the email provider regularly, the frequencey is controlled by a variety of factors and the manufacturer. Again, the credentials stay in the device.
4. COI introduced the idea of WebPush for IMAP, in this case the email backend informs an intermediate push service that then sends a push notification to the app. The benefit is that the credentials never leave the device and you will get informed immediately. However, so far no mail service provider supports this proposal.

 For now I would start with option 3 and then add option 2 at a later point. I am very open for suggestions!

**Comment by RaviVarsani** [comment]
any progress on this Feature? @robert-virkus @RaviGaruda

**Comment by robert-virkus** [comment]
Not really, right now I am working on #11 
I have, however, found these possibly fitting packages:

- https://pub.dev/packages/background_fetch
- https://pub.dev/packages/flutter_local_notifications

**Comment by robert-virkus** [comment]
Note that for iOS the background setup is still required compare https://github.com/transistorsoft/flutter_background_fetch/blob/master/help/INSTALL-IOS.md
