### ISSUE TITLE
Pub getting failed for latest commit 

### ISSUE THREAD

**Issue by RaviGaruda** [Enough-Software/enough_mail_app#35]
Because enough_mail_app depends on **enough_mail_flutter** from git which depends on **enough_media ^0.2.0**, enough_media from hosted is required.
**So, because enough_mail_app depends on enough_media from git, version solving failed.**
pub upgrade failed (1; So, because enough_mail_app depends on enough_media from git, version solving failed.)

**Comment by robert-virkus** [comment]
oops, sorry. Have pushed a new pubspec version to `enough_mail_flutter`, so please try again. You might need to call 
`flutter pub upgrade` to ensure that you are on the latest version of all referenced projects.

Please close when it now works for you.

**Comment by RaviGaruda** [comment]
yep now it working after calling **flutter pub upgrade**. now i closed this bug as it working.
