### ISSUE TITLE
Messages that contain a specific word

### ISSUE THREAD

**Issue by barilki** [Enough-Software/enough_mail_app#36]
Hi, I'm using the high level API, and I want to only retrieve messages that contain a particular word(TEST), but nothing seems to be working. It shows me all the messages that exist in the email.

code: 
final mailboxes =
      await mailClient.listMailboxesAsTree(createIntermediate: false);
      print(mailboxes);
      await mailClient.selectInbox();
      await mailClient.searchMessages(MailSearch("TEST",SearchQueryType.allTextHeaders));
      final messages = await mailClient.fetchMessages(count: 20);
      for (final msg in messages) {
        printMessage(msg);
      }

Thank you!

**Comment by robert-virkus** [comment]
This question belongs to https://github.com/Enough-Software/enough_mail/issues but I can answer it here:

When you search, you need to use the search result for fetching the matching messages, in your code example:
```dart
final searchResult = await mailClient.searchMessages(MailSearch("TEST",SearchQueryType.allTextHeaders));
if (searchResult.size > 0) {
  // the first page of search results is already pre-cached:
  for (final msg in searchResult.messages.elements) {
    printMessage(msg);
  }
  // if you have more search results, you need to get them individually:
  if (searchResult.size > searchResult.messages.pageSize) {
    final secondPageSequence = searchResult.messageSequence.subsequenceFromPage(2, searchResult.messages.pageSize);
    final secondPageMessages = await mailClient.fetchMessageSequence(secondPageSequence);
    // [...]
  }
}
```

Writing this I begin to think that this code is quite complex, so I plan to ease it in the future, compare this issue: https://github.com/Enough-Software/enough_mail/issues/119

Please close this issue if this answers your question.

**Comment by barilki** [comment]
Thank you so much!
