### ISSUE TITLE
feature request: open links in browser

### ISSUE THREAD

**Issue by Sinasta** [Enough-Software/enough_mail_app#56]
would it be possible to redirect links if they have been clicked to the main browser? thank you

**Comment by robert-virkus** [comment]
Do I assume correctly that you are

- on iOS
- while reading mail
- tap on a link
?

In that case I could introduce an iOS-specific option to open links directly in the web view, for example.

**Comment by Sinasta** [comment]
sorry u forgot to specifiy that im on android

**Comment by robert-virkus** [comment]
Thanks for the feedback. On Android links open by default in the web browser. 
There are 2 possiblities for your problem that I can think of:
1. You have chosen a different app and selected "always open with XXX" at some point
2. The link is not recognized as a link, meaning you cannot click it at all

What happens in your case?

**Comment by robert-virkus** [comment]
This was a bug in launcher which I am working around now
