### ISSUE TITLE
can't add an email account using the detailed configuration

### ISSUE THREAD

**Issue by sebastianfastert** [Enough-Software/enough_mail_app#59]
Hi,

I was able to connect my gmail account without problems. But I can't add an account, where manual server configuration is necessary. When pressing the save button, nothing happens (also no error message).

Thanks for all your work!
Greetings,
Sebastian

**Comment by robert-virkus** [comment]
Thanks for your report, will look into this!

**Comment by robert-virkus** [comment]
@tallinn1960 already fixed it (thanks again!) :-) 
I just submitted a new beta release, should be live on Google Play within a day or two and on iOS in a couple of hours.

**Comment by robert-virkus** [comment]
update is now online
