### ISSUE TITLE
conflicting deps on enough_platform_widgets package

### ISSUE THREAD

**Issue by maks** [Enough-Software/enough_mail_app#62]
Hi I grabbed current main branch but this initia `pub get` fails as it seems there is a version conflict between the direct dep on enough_platform_widgets and the transitive dep from `enough_html_editor`:

```
[enough_mail_app] flutter pub get
Running "flutter pub get" in enough_mail_app...                 
Because enough_mail_app depends on enough_html_editor from git which depends on enough_platform_widgets ^0.3.0, enough_platform_widgets from hosted is required.
So, because enough_mail_app depends on enough_platform_widgets from git, version solving failed.
pub get failed (1; So, because enough_mail_app depends on enough_platform_widgets from git, version solving failed.)
```

**Comment by robert-virkus** [comment]
Thanks for your report, this should be fixed now in the enough_html_editor project. Please run `flutter pub upgrade` to retrieve the latest state. If it works for you please close this issue.

**Comment by maks** [comment]
Brillant, thanks for working on it so quickly! yes thats fixed the issue. 
I'm actually giving it a go as a Linux app and so far apart from missing Linux support from `background_fetch` it runs well enough to get to the on-boarding screen:

![Screenshot from 2022-01-31 19-44-54](https://user-images.githubusercontent.com/71999/151763634-6eac0a26-776f-477f-9304-ee97bf6a9c2c.png)

signin to my mail account:
 
![image](https://user-images.githubusercontent.com/71999/151764004-4185aada-7e59-4529-934e-afff610ea49e.png)

and get my inbox listing - thank you for making the app so nicely non platform dependent! 👍🏻 
I did hit a problem with the webview not working for mail contents - I'll try to get that fixed and submit a PR as soon as I get a chance.
