### ISSUE TITLE
Error when run code

### ISSUE THREAD

**Issue by nvThanh** [Enough-Software/enough_mail_app#71]
I got this error when i try to download and run code,
Please tell me how to fix

../flutter/.pub-cache/hosted/pub.dartlang.org/introduction_screen-3.0.2/lib/src/introduction_screen.dart:434:35: Error: The method 'elementAtOrNull' is defined in multiple extensions for 'List<ScrollController?>' and neither is more specific.
 - 'List' is from 'dart:core'.
 - 'ScrollController' is from 'package:flutter/src/widgets/scroll_controller.dart' ('../flutter/packages/flutter/lib/src/widgets/scroll_controller.dart').
Try using an explicit extension application of the wanted extension or hiding unwanted extensions from scope.
                                ?.elementAtOrNull(index),
                                  ^^^^^^^^^^^^^^^
../flutter/.pub-cache/hosted/pub.dartlang.org/collection-1.17.0/lib/src/list_extensions.dart:271:6: Context: This is one of the extension members.
  E? elementAtOrNull(int index) => (index < length) ? this[index] : null;
     ^^^^^^^^^^^^^^^
../flutter/.pub-cache/hosted/pub.dartlang.org/introduction_screen-3.0.2/lib/src/helper.dart:6:6: Context: This is one of the extension members.
  T? elementAtOrNull(int index) {
     ^^^^^^^^^^^^^^^

**Comment by nvThanh** [comment]
<img width="1336" alt="Screenshot 2022-11-11 at 9 59 29 AM" src="https://user-images.githubusercontent.com/11532373/201255255-64598243-2467-47b7-a046-ef0d8f966c65.png">

**Comment by robert-virkus** [comment]
This should now we be resolved
